// TODO Implement this library.// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIpEzdgEmOMu3CatLLLyPH9Ol9rz55MtM',
    appId: '1:180146100143:web:6c0f885a587deb6decc15a',
    messagingSenderId: '180146100143',
    projectId: 'balancematch-322fe',
    authDomain: 'balancematch-322fe.firebaseapp.com',
    storageBucket: 'balancematch-322fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd6JUMR6JQl37av3fxjocqZJefySXeR_0',
    appId: '1:180146100143:android:0cce04a1f992c9a6ecc15a',
    messagingSenderId: '180146100143',
    projectId: 'balancematch-322fe',
    storageBucket: 'balancematch-322fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrE5FVsDd3tWhAE3rR1khMsWcINXeEl7o',
    appId: '1:180146100143:ios:13936edad8c3b877ecc15a',
    messagingSenderId: '180146100143',
    projectId: 'balancematch-322fe',
    storageBucket: 'balancematch-322fe.firebasestorage.app',
    iosBundleId: 'com.balancematch.balancematch',
  );
}
